INSERT INTO AUTOMOVEIS_TB (id, marca, nome, preco, date_created)
SELECT 1, 'Toyota', 'Corolla XEI', 95000.00, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM AUTOMOVEIS_TB WHERE id = 1);

INSERT INTO AUTOMOVEIS_TB (id, marca, nome, preco, date_created)
SELECT 2, 'Honda', 'Civic Touring', 105000.00, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM AUTOMOVEIS_TB WHERE id = 2);

INSERT INTO AUTOMOVEIS_TB (id, marca, nome, preco, date_created)
SELECT 3, 'Chevrolet', 'Onix LT', 78000.00, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM AUTOMOVEIS_TB WHERE id = 3);

INSERT INTO AUTOMOVEIS_TB (id, marca, nome, preco, date_created)
SELECT 4, 'Volkswagen', 'Golf GTI', 132000.00, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM AUTOMOVEIS_TB WHERE id = 4);
